name: quant_chart
description: A k chart in FLutter.
version: 0.0.1
homepage: https://github.com/KevlarTheGreat/quant_chart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
