name: k_chart_flutter
description: A k chart in FLutter.
version: 0.1.0
homepage: https://github.com/fxwalletOfficial/k_chart_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
